import { CommonModule, DatePipe } from '@angular/common';
import { Component, OnInit, ViewChild } from '@angular/core';
import { FormBuilder, FormGroup, FormsModule, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { MessageService } from 'primeng/api';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { SelectModule } from 'primeng/select';
import { PasswordModule } from 'primeng/password';
import { TooltipModule } from 'primeng/tooltip';
import { DialogModule } from 'primeng/dialog';
import { FileUploadModule } from 'primeng/fileupload';
import { DividerModule } from 'primeng/divider';
import { ToastModule } from 'primeng/toast';
import { CheckboxModule } from 'primeng/checkbox';
import { InputNumberModule } from 'primeng/inputnumber';

// Image Cropper
import {
  Dimensions,
  ImageCroppedEvent,
  ImageCropperModule,
  ImageTransform,
} from 'ngx-image-cropper';

@Component({
  selector: 'app-c-users',
  standalone: true,
  imports: [
    CommonModule,
    ReactiveFormsModule,
    FormsModule,
    ButtonModule,
    InputTextModule,
    SelectModule,
    PasswordModule,
    TooltipModule,
    DialogModule,
    FileUploadModule,
    DividerModule,
    ToastModule,
    ImageCropperModule,
    CheckboxModule,
    InputNumberModule
  ],
  providers: [MessageService, DatePipe],
  templateUrl: './c-users.html',
  styleUrls: ['./c-users.scss'],
})
export class CUsers implements OnInit {
  @ViewChild('fileInput') fileInput!: any;

  userForm!: FormGroup;
  datePipe = new DatePipe('en-US');

  // Dropdown Lists
  companyList: any[] = [];
  branchList: any[] = [];
  roleList: any[] = [];
  statusList = [
    { label: 'Active', value: 1 },
    { label: 'Inactive', value: 0 },
    { label: 'Pending', value: 2 },
    { label: 'Locked', value: 3 }
  ];

  // Theme Dropdown
  themeList = [
    { label: 'Light', value: 'light' },
    { label: 'Dark', value: 'dark' },
    { label: 'System Default', value: 'system' }
  ];

  // Profile Picture
  profilePreviewUrl: string | null = null;
  selectedFile: File | null = null;
  isImageCleared: boolean = false;

  // States
  isSaving: boolean = false;
  isEditMode: boolean = false;
  isViewMode: boolean = false;

  // Current User ID (for CreatedBy field)
  currentUserId: number = 1; // This should come from your auth service

  // ============================================
  // IMAGE CROPPER PROPERTIES
  // ============================================
  showImageCropper: boolean = false;
  imageChangedEvent: any = '';
  croppedImage: any = '';
  canvasRotation: number = 0;
  rotation: number = 0;
  scale: number = 1;
  showCropper: boolean = false;
  containWithinAspectRatio: boolean = false;
  transform: ImageTransform = {};
  _CropImage: File | undefined;
  fileName: string | null = null;

  constructor(
    private fb: FormBuilder,
    private messageService: MessageService,
    private router: Router
  ) {}

  ngOnInit() {
    this.initForm();
    this.loadDropdownData();
  }

  // ============================================
  // INITIALIZATION
  // ============================================

  initForm() {
    this.userForm = this.fb.group({
      // UserId - Auto-generated by database
      UserId: [0],

      // Required fields (matching database column names exactly)
      CompanyId: [null, [Validators.required]],
      BranchId: [null, [Validators.required]],
      RoleId: [null, [Validators.required]],
      Username: [null, [Validators.required, Validators.minLength(3), Validators.maxLength(50)]],
      PasswordHash: [null, [Validators.required, Validators.minLength(6)]],
      FullName: [null, [Validators.required, Validators.maxLength(100)]],

      // Optional fields
      Email: [null, [Validators.email, Validators.maxLength(100)]],
      Phone: [null, [Validators.maxLength(20)]],

      // Avatar fields
      AvatarName: [null],
      AvatarUrl: [null],

      // Status
      Status: [1, [Validators.required]],

      // Preferences
      Theme: ['system'],

      // Security fields
      IsLocked: [false],
      FailedLoginAttempts: [0],
      LockoutEndDate: [null],
      PasswordChangedDate: [null],
      MustChangePassword: [false],
      LoginExpiryDays: [30],

      // LastLogin - Will be set by database initially
      LastLogin: [null],

      // Audit fields
      CreatedBy: [this.currentUserId, [Validators.required]],
      CreatedDate: [this.datePipe.transform(new Date(), 'yyyy-MM-dd HH:mm:ss.SSS')],
      ModifiedBy: [null],
      ModifiedDate: [null]
    });
  }

  loadDropdownData() {
    // TODO: Load from your service
    // Example placeholder data
    this.companyList = [
      { label: 'Company A', value: 1 },
      { label: 'Company B', value: 2 },
      { label: 'Company C', value: 3 }
    ];

    this.branchList = [
      { label: 'Branch 1', value: 1 },
      { label: 'Branch 2', value: 2 },
      { label: 'Branch 3', value: 3 }
    ];

    this.roleList = [
      { label: 'Admin', value: 1 },
      { label: 'Manager', value: 2 },
      { label: 'User', value: 3 }
    ];
  }

  // ============================================
  // IMAGE CROPPER METHODS
  // ============================================

  onFileSelected(event: Event) {
    const input = event.target as HTMLInputElement;
    if (!input.files || !input.files[0]) return;

    const file = input.files[0];
    const allowedTypes = ['image/png', 'image/jpeg', 'image/jpg'];
    const maxSize = 2 * 1024 * 1024; // 2MB

    if (!allowedTypes.includes(file.type)) {
      this.showMessage('warn', 'Invalid File', 'Only PNG and JPEG images are allowed.');
      this.resetFileInput();
      return;
    }

    if (file.size > maxSize) {
      this.showMessage('warn', 'File Too Large', 'File size must be less than 2MB.');
      this.resetFileInput();
      return;
    }

    const reader = new FileReader();
    reader.onload = () => {
      const img = new Image();
      img.onload = () => {
        if (img.width < 140 || img.height < 60) {
          this.showMessage('warn', 'Image Too Small', 'Image must be at least 140x60 pixels.');
          this.resetFileInput();
          return;
        }

        this.imageChangedEvent = { target: { files: [file] } };
        this.showImageCropper = true;
        this.fileName = file.name;
      };
      img.src = reader.result as string;
    };
    reader.readAsDataURL(file);
  }

  resetFileInput() {
    if (this.fileInput) {
      this.fileInput.nativeElement.value = '';
    }
  }

  imageLoaded() {
    this.showCropper = true;
  }

  cropperReady(dimensions: Dimensions) {
    console.log('Cropper ready:', dimensions);
  }

  loadImageFailed() {
    this.showMessage('error', 'Load Failed', 'Failed to load image. Please try another file.');
    this.showImageCropper = false;
  }

  imageCropped(event: ImageCroppedEvent) {
    this.croppedImage = event.objectUrl || event.base64 || '';
  }

  zoomIn() {
    this.scale += 0.1;
    this.transform = { ...this.transform, scale: this.scale };
  }

  zoomOut() {
    this.scale = Math.max(0.1, this.scale - 0.1);
    this.transform = { ...this.transform, scale: this.scale };
  }

  rotateLeft() {
    this.canvasRotation--;
  }

  rotateRight() {
    this.canvasRotation++;
  }

  resetCropper() {
    this.scale = 1;
    this.rotation = 0;
    this.canvasRotation = 0;
    this.transform = {};
  }

  cancelCrop() {
    this.showImageCropper = false;
    this.croppedImage = '';
    this.resetCropper();
    this.resetFileInput();
  }

  applyCrop() {
    if (!this.croppedImage) return;

    this.showImageCropper = false;
    this.profilePreviewUrl = this.croppedImage;
    this.fileName = this.generateFileName();
    this.isImageCleared = false;

    this.blobUrlToFile(this.croppedImage, this.fileName).then((file) => {
      this._CropImage = file;
      this.userForm.patchValue({
        AvatarName: this.fileName,
        AvatarUrl: this.fileName
      });
    });

    this.resetCropper();
  }

  async blobUrlToFile(blobUrl: string, fileName: string): Promise<File> {
    const response = await fetch(blobUrl);
    const blob = await response.blob();
    return new File([blob], fileName, { type: blob.type });
  }

  generateFileName(): string {
    const timestamp = new Date().valueOf();
    const randomStr = Math.random().toString(36).substring(2, 7);
    return `${timestamp}_${randomStr}.png`;
  }

  removePhoto() {
    this.profilePreviewUrl = null;
    this.selectedFile = null;
    this._CropImage = undefined;
    this.croppedImage = '';
    this.fileName = null;
    this.isImageCleared = true;

    this.userForm.patchValue({
      AvatarName: '',
      AvatarUrl: ''
    });

    this.resetFileInput();
  }

  // ============================================
  // FORM SUBMISSION
  // ============================================

  saveUser() {
    // Mark all fields as touched
    Object.keys(this.userForm.controls).forEach(key => {
      const control = this.userForm.get(key);
      control?.markAsTouched();
      control?.updateValueAndValidity();
    });

    if (!this.userForm.valid) {
      this.showMessage('warn', 'Validation Error', 'Please fill all required fields correctly.');
      return;
    }

    this.isSaving = true;

    let user = this.userForm.getRawValue();

    if (this._CropImage) {
      user.AvatarName = this._CropImage.name;
      user.AvatarUrl = this._CropImage.name;
    } else if (this.isImageCleared) {
      user.AvatarUrl = '';
      user.AvatarName = '';
    }

    const data = {
      User: user,
      IsImageCleared: this.isImageCleared
    };

    const formData = this.prepareFormData(data, this._CropImage);

    // Simulate API call - Replace with your actual service call
    console.log('User Data to Save:', data);
    console.log('Form Data:', formData);

    setTimeout(() => {
      this.isSaving = false;
      this.isImageCleared = false;
      this.showMessage('success', 'Success', 'User created successfully!');
      this.resetForm();
      // Navigate back to list after save
      // this.router.navigate(['/users']);
    }, 2000);
  }

  prepareFormData(data: any, file?: File): FormData {
    const formData = new FormData();

    if (file) {
      formData.append('files', file, file.name);
    }

    formData.append('strUser', JSON.stringify(data));
    return formData;
  }

  resetForm() {
    this.isImageCleared = false;
    this.removePhoto();
    this.isImageCleared = false;

    this.userForm.reset({
      UserId: 0,
      CompanyId: null,
      BranchId: null,
      RoleId: null,
      Username: null,
      PasswordHash: null,
      FullName: null,
      Email: null,
      Phone: null,
      AvatarName: null,
      AvatarUrl: null,
      Status: 1,
      // Preferences
      Theme: 'system',
      // Security fields
      IsLocked: false,
      FailedLoginAttempts: 0,
      LockoutEndDate: null,
      PasswordChangedDate: null,
      MustChangePassword: false,
      LoginExpiryDays: 30,
      // Other fields
      LastLogin: null,
      CreatedBy: this.currentUserId,
      CreatedDate: this.datePipe.transform(new Date(), 'yyyy-MM-dd HH:mm:ss.SSS'),
      ModifiedBy: null,
      ModifiedDate: null
    });

    Object.keys(this.userForm.controls).forEach(key => {
      const control = this.userForm.get(key);
      control?.setErrors(null);
      control?.markAsUntouched();
      control?.markAsPristine();
    });
  }

  clearForm() {
    this.resetForm();
  }

  // ============================================
  // UTILITY METHODS
  // ============================================

  showMessage(severity: string, summary: string, detail: string) {
    this.messageService.add({
      key: 'br',
      severity,
      summary,
      detail,
      life: 3000
    });
  }

  // ============================================
  // NAVIGATION
  // ============================================
  goBack() {
    this.router.navigate(['/users']);
  }
}