import { DatePipe } from '@angular/common';
import { Component, inject, OnInit, signal } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule, Validators } from '@angular/forms';
import { ActivatedRoute, Router } from '@angular/router';
import { MessageService } from 'primeng/api';
import { ButtonModule } from 'primeng/button';
import { InputTextModule } from 'primeng/inputtext';
import { SelectModule } from 'primeng/select';
import { ToastModule } from 'primeng/toast';
import { TextareaModule } from 'primeng/textarea';
import { BranchService } from '../../../../services/api/branch-service';
import { ErrorHandlerService } from '../../../../services/helpers';

@Component({
  selector: 'app-c-branchs',
  standalone: true,
  imports: [
    ReactiveFormsModule,
    ButtonModule,
    InputTextModule,
    SelectModule,
    ToastModule,
    TextareaModule
  ],
  providers: [MessageService, DatePipe],
  templateUrl: './c-branchs.html',
  styleUrls: ['./c-branchs.scss'],
})
export class CBranchs implements OnInit {
  // Inject dependencies using inject function
  private fb = inject(FormBuilder);
  private messageService = inject(MessageService);
  private branchService = inject(BranchService);
  private errorHandler = inject(ErrorHandlerService);
  private router = inject(Router);
  private route = inject(ActivatedRoute);
  private datePipe = inject(DatePipe);

  // Form
  branchForm!: FormGroup;

  // Dropdown Lists
  statusList = signal<SystemMetadatum[]>([]);
  userList = signal<any[]>([]);

  // States
  isSaving = signal(false);
  isEditMode = signal(false);
  isViewMode = signal(false);

  // Route params
  private branchId = 0;

  // Current User ID (should come from auth service)
  private currentUserId = 2;

  ngOnInit() {
    this.initForm();
    this.checkRouteParams();
    this.loadPageData();
  }

  private checkRouteParams() {
    const id = this.route.snapshot.queryParams['id'];
    const mode = this.route.snapshot.queryParams['mode'];

    if (id) {
      this.branchId = +id;
      this.isEditMode.set(mode === 'edit');
      this.isViewMode.set(mode === 'view');
    }
  }

  private loadPageData() {
    const params = { BranchId: this.branchId, CompanyId: 1 };
    this.branchService.PageInit(params).subscribe({
      next: (response) => {
        const data = response.Data;
        this.statusList.set(data.StatusList || []);
        this.userList.set(data.UsersList || []);
        if (data.branch && this.branchId > 0) {
          this.branchForm.patchValue(data.branch);
          if (this.isViewMode()) {
            this.branchForm.disable();
          }
        }
      },
      error: () => {
        this.showMessage('error', 'Error', 'Failed to initialize the page.');
      }
    });
  }

  // ============================================
  // INITIALIZATION
  // ============================================

  initForm() {
    this.branchForm = this.fb.group({
      // BranchId - Auto-generated by database
      BranchId: [0],
      CompanyId: [1],
      // Required fields
      BranchCode: [null],
      BranchName: [null, [Validators.required, Validators.maxLength(100)]],

      // Optional fields
      Address: [null, [Validators.maxLength(500)]],
      Phone: [null, [Validators.maxLength(20)]],
      Manager: [null, [Validators.maxLength(100)]],

      // Status
      Status: [1, [Validators.required]],

      // Audit fields
      CreatedBy: [this.currentUserId, [Validators.required]],
      CreatedDate: [this.datePipe.transform(new Date(), 'yyyy-MM-dd HH:mm:ss.SSS')],
      ModifiedBy: [null],
      ModifiedDate: [null]
    });
  }

  // ============================================
  // FORM SUBMISSION
  // ============================================

  saveBranch() {
    // Mark all fields as touched
    this.branchForm.markAllAsTouched();

    if (this.branchForm.invalid) {
      this.showMessage('warn', 'Validation Error', 'Please fill all required fields correctly.');
      return;
    }

    this.isSaving.set(true);

    const data = { Branch: this.branchForm.getRawValue() };
    const saveObservable = this.isEditMode()
      ? this.branchService.Update(data)
      : this.branchService.Create(data);

    saveObservable.subscribe({
      next: (response) => {
        this.isSaving.set(false);
        this.errorHandler.showSuccess(response.Title, response.Message || 'Branch saved successfully.');
        this.goBack();
      },
      error: () => {
        this.isSaving.set(false);
        this.showMessage('error', 'Error', 'Failed to save branch. Please try again.');
      }
    });
  }

  clearForm() {
    this.branchForm.reset({
      BranchId: 0,
      CompanyId: 1,
      BranchCode: null,
      BranchName: null,
      Address: null,
      Phone: null,
      Manager: null,
      Status: 1,
      CreatedBy: this.currentUserId,
      CreatedDate: this.datePipe.transform(new Date(), 'yyyy-MM-dd HH:mm:ss.SSS'),
      ModifiedBy: null,
      ModifiedDate: null
    });
  }

  // ============================================
  // UTILITY METHODS
  // ============================================

  private showMessage(severity: string, summary: string, detail: string) {
    this.messageService.add({
      key: 'br',
      severity,
      summary,
      detail,
      life: 3000
    });
  }

  // ============================================
  // NAVIGATION
  // ============================================

  goBack() {
    this.router.navigate(['/home/v-branchs']);
  }
}
